version: "3.9"
services:
  backend:
    env_file: "/home/linuxuser/prod.env" 
    container_name: backend
    restart: always
    build:
      dockerfile: backend.Dockerfile
      context: .
      args:
        - VITE_MAPBOX_API_KEY=$VITE_MAPBOX_API_KEY
    ports:
      - "8080:8080"