name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to production
      run: |
        echo "Deploying to production"
        source /home/linuxuser/prod.env 
        export VITE_MAPBOX_API_KEY=$VITE_MAPBOX_API_KEY
        docker compose build
        docker compose up -d
        echo "Deployed!"